[unstable]
# Behind the scenes, this flag enables the mem feature of the compiler_builtins crate.
# The effect of this is that the #[no_mangle] attribute is applied to the memcpy etc. implementations of the crate,
# which makes them available to the linker.
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]


[build]
# override the default target
target = "x86_64-ruost.json"

[target.'cfg(target_os = "none")'] # applies to all targets whose target configuration file’s "os" field is set to "none"
runner = "bootimage runner" # command ran when executing "cargo run"